// @ts-check

// See: https://docusaurus.io/docs/sidebar
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Example sidebar that just lists all docs in
  // alphabetical order from file structure in ./docs
  example: [{ type: "autogenerated", dirName: "." }],
};
