// @ts-check

// See: https://docusaurus.io/docs/sidebar
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lockSidebar: [
    {
      type: "category",
      label: "Locks",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Locks",
        description: "This is an auto-generated list of all the locks.",
        slug: "upgrades/locks",
      },
      items: [{ type: "autogenerated", dirName: "upgrades/locks" }],
    },
  ],
  characterSidebar: [
    {
      type: "category",
      label: "Characters",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Characters",
        description: "This is an auto-generated list of all the locks.",
        slug: "lore/characters",
      },
      items: [{ type: "autogenerated", dirName: "lore/characters" }],
    },
  ],
  eventSidebar: [
    {
      type: "category",
      label: "Events",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Events",
        description: "This is an auto-generated list of all events.",
        slug: "lore/events",
      },
      items: [{ type: "autogenerated", dirName: "lore/events" }],
    },
  ],
  scriptingSidebar: [
    {
      type: "category",
      label: "scripting",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Events",
        description: "This is an auto-generated list of all events.",
        slug: "scripting",
      },
      items: [{ type: "autogenerated", dirName: "scripting" }],
    },
  ],
};

module.exports = sidebars;
